"""
FINAL AI RECOMMENDATION ENGINE

FINAL OUTPUT - ONLY:

1. Sell Now vs Wait
2. Choose Market
3. Choose Buyer
4. Expected Net Profit
5. Risk Level
6. Confidence
7. Reason

This is the final decision aggregation layer.

It uses outputs already generated by:

    AI Engine
        ↓
    Decision Intelligence Engine
        ↓
    Execution & Matching
        ↓
    Final AI Recommendation

IMPORTANT:

    No new ML model
    No model retraining
    No new dataset
    No dataset modification
    No fake predictions
    No AI Agent
    No architecture change

The Sell/Wait decision is dynamically determined from:

    Expected Net Profit
    Risk Level
    Confidence

Possible final decisions:

    SELL NOW
    SELL WITH CAUTION
    WAIT / REASSESS
"""

from pathlib import Path
import sys
import traceback


# ======================================================================
# PATH SETUP
# ======================================================================

CURRENT_FILE = Path(__file__).resolve()

RECOMMENDATION_DIR = CURRENT_FILE.parent
APP_DIR = RECOMMENDATION_DIR.parent
BACKEND_DIR = APP_DIR.parent
PROJECT_ROOT = BACKEND_DIR.parent

for path in [
    RECOMMENDATION_DIR,
    APP_DIR,
    BACKEND_DIR,
    PROJECT_ROOT,
]:
    if str(path) not in sys.path:
        sys.path.insert(0, str(path))


# ======================================================================
# TEST TRANSACTION
# ======================================================================

CROP = "Bajra"

QUANTITY_KG = 887.0

QUALITY_GRADE = "C"

ORIGIN_DISTRICT = "Kheda"

ORIGIN_MARKET = "Kheda APMC"

CURRENT_PRICE = 7591.84


# ======================================================================
# FINAL AI RECOMMENDATION ENGINE
# ======================================================================

class FinalAIRecommendationEngine:

    """
    Final recommendation aggregation engine.

    No machine-learning model is trained here.

    The engine combines already available outputs and produces
    exactly seven final recommendation fields.
    """

    def __init__(self):

        print()
        print("=" * 70)
        print("FINAL AI RECOMMENDATION ENGINE")
        print("=" * 70)

        print()
        print("✓ Existing architecture will be used.")
        print("✓ No new ML model.")
        print("✓ No new dataset.")
        print("✓ No model retraining.")
        print("✓ No dataset modification.")
        print("✓ No AI Agent.")

    # ==================================================================
    # NUMERIC HELPER
    # ==================================================================

    @staticmethod
    def _number(
        value,
        default=0.0,
    ):
        """
        Safely converts a value into float.
        """

        if value is None:
            return default

        if isinstance(
            value,
            (int, float),
        ):
            return float(value)

        text = str(value)

        text = (
            text
            .replace("₹", "")
            .replace(",", "")
            .replace("%", "")
            .strip()
        )

        try:
            return float(text)

        except Exception:
            return default

    # ==================================================================
    # STRING HELPER
    # ==================================================================

    @staticmethod
    def _clean(
        value,
        default="NOT AVAILABLE",
    ):
        """
        Safely converts values into non-empty strings.
        """

        if value is None:
            return default

        text = str(value).strip()

        if not text:
            return default

        return text

    # ==================================================================
    # DYNAMIC SELL NOW VS WAIT
    # ==================================================================

    def determine_sell_wait(
        self,
        decision_result,
        net_profit,
        risk_level,
        confidence,
    ):
        """
        Dynamically determines the final Sell/Wait decision.

        Priority:

            1. Expected Net Profit
            2. Risk Level
            3. Confidence

        Possible outputs:

            SELL NOW
            SELL WITH CAUTION
            WAIT / REASSESS

        IMPORTANT:

        The Decision Intelligence recommendation is NOT blindly copied.

        The final recommendation is based primarily on the
        execution-level expected net profit.
        """

        risk_level = str(
            risk_level
        ).strip().upper()

        confidence = float(
            confidence
        )

        net_profit = float(
            net_profit
        )

        # ==============================================================
        # RULE 1
        # NEGATIVE PROFIT
        # ==============================================================

        if net_profit < 0:

            return "WAIT / REASSESS"

        # ==============================================================
        # RULE 2
        # ZERO PROFIT
        # ==============================================================

        if net_profit == 0:

            return "WAIT / REASSESS"

        # ==============================================================
        # RULE 3
        # POSITIVE PROFIT + LOW RISK + HIGH CONFIDENCE
        # ==============================================================

        if (
            net_profit > 0
            and risk_level == "LOW"
            and confidence >= 70
        ):

            return "SELL NOW"

        # ==============================================================
        # RULE 4
        # POSITIVE PROFIT + MEDIUM RISK
        # ==============================================================

        if (
            net_profit > 0
            and risk_level == "MEDIUM"
        ):

            return "SELL WITH CAUTION"

        # ==============================================================
        # RULE 5
        # POSITIVE PROFIT + HIGH RISK
        # ==============================================================

        if (
            net_profit > 0
            and risk_level == "HIGH"
        ):

            return "SELL WITH CAUTION"

        # ==============================================================
        # RULE 6
        # POSITIVE PROFIT + VERY LOW CONFIDENCE
        # ==============================================================

        if (
            net_profit > 0
            and confidence < 50
        ):

            return "WAIT / REASSESS"

        # ==============================================================
        # RULE 7
        # POSITIVE PROFIT + MODERATE CONFIDENCE
        # ==============================================================

        if (
            net_profit > 0
            and 50 <= confidence < 70
        ):

            return "SELL WITH CAUTION"

        # ==============================================================
        # SAFETY FALLBACK
        # ==============================================================

        return "WAIT / REASSESS"

    # ==================================================================
    # CHOOSE MARKET
    # ==================================================================

    def choose_market(
        self,
        decision_result,
        logistics_result,
    ):
        """
        Selects the best market from existing Decision Intelligence
        and Logistics outputs.
        """

        market = self._clean(
            decision_result.get(
                "best_market"
            ),
            "",
        )

        if market:
            return market

        market = self._clean(
            decision_result.get(
                "market"
            ),
            "",
        )

        if market:
            return market

        market = self._clean(
            logistics_result.get(
                "destination"
            ),
            "",
        )

        if market:
            return market

        market = self._clean(
            logistics_result.get(
                "best_destination"
            ),
            "",
        )

        if market:
            return market

        return "NOT AVAILABLE"

    # ==================================================================
    # CHOOSE BUYER
    # ==================================================================

    def choose_buyer(
        self,
        decision_result,
        profit_result,
        risk_result,
        auction_result,
    ):
        """
        Selects the buyer using existing execution outputs.

        Priority:

            Net Profit Optimization
            Risk-Aware Bidding
            AI Auction
        """

        # --------------------------------------------------------------
        # NET PROFIT OPTIMIZATION
        # --------------------------------------------------------------

        buyer = self._clean(
            profit_result.get(
                "buyer_name"
            ),
            "",
        )

        if buyer:
            return buyer

        buyer = self._clean(
            profit_result.get(
                "recommended_buyer"
            ),
            "",
        )

        if buyer:
            return buyer

        # --------------------------------------------------------------
        # RISK-AWARE BIDDING
        # --------------------------------------------------------------

        buyer = self._clean(
            risk_result.get(
                "buyer_name"
            ),
            "",
        )

        if buyer:
            return buyer

        buyer = self._clean(
            risk_result.get(
                "recommended_buyer"
            ),
            "",
        )

        if buyer:
            return buyer

        # --------------------------------------------------------------
        # AI AUCTION
        # --------------------------------------------------------------

        buyer = self._clean(
            auction_result.get(
                "buyer_name"
            ),
            "",
        )

        if buyer:
            return buyer

        buyer = self._clean(
            auction_result.get(
                "winner"
            ),
            "",
        )

        if buyer:
            return buyer

        return "NOT AVAILABLE"

    # ==================================================================
    # EXPECTED NET PROFIT
    # ==================================================================

    def get_net_profit(
        self,
        decision_result,
        profit_result,
    ):
        """
        Execution-level Net Profit Optimization gets priority.

        Decision Intelligence net profit is used only if the
        execution-level result is unavailable.
        """

        candidates = [

            profit_result.get(
                "net_profit"
            ),

            profit_result.get(
                "expected_net_profit"
            ),

            decision_result.get(
                "net_profit"
            ),

            decision_result.get(
                "expected_net_profit"
            ),

        ]

        for value in candidates:

            if value is not None:

                return self._number(
                    value
                )

        return 0.0

    # ==================================================================
    # RISK LEVEL
    # ==================================================================

    def get_risk_level(
        self,
        decision_result,
        risk_result,
    ):
        """
        Uses existing risk outputs.

        Risk-Aware Bidding is preferred over the broader
        Decision Intelligence risk level because the final
        recommendation concerns the actual selected execution.
        """

        # --------------------------------------------------------------
        # Risk-Aware Bidding
        # --------------------------------------------------------------

        candidates = [

            risk_result.get(
                "risk_level"
            ),

            decision_result.get(
                "risk_level"
            ),

        ]

        for value in candidates:

            if value is not None:

                text = str(
                    value
                ).strip()

                if text:

                    return text.upper()

        # --------------------------------------------------------------
        # Numeric risk fallback
        # --------------------------------------------------------------

        risk_score = None

        for key in [
            "combined_risk",
            "risk_score",
        ]:

            if key in risk_result:

                risk_score = self._number(
                    risk_result[key],
                    None,
                )

                if risk_score is not None:
                    break

        if risk_score is None:

            for key in [
                "risk_score",
                "decision_risk_score",
            ]:

                if key in decision_result:

                    risk_score = self._number(
                        decision_result[key],
                        None,
                    )

                    if risk_score is not None:
                        break

        if risk_score is not None:

            if risk_score < 30:
                return "LOW"

            if risk_score < 60:
                return "MEDIUM"

            return "HIGH"

        return "NOT AVAILABLE"

    # ==================================================================
    # CONFIDENCE
    # ==================================================================

    def get_confidence(
        self,
        decision_result,
    ):
        """
        Gets the existing Decision Intelligence confidence.

        If the source provides a 0-1 value, it is converted to
        a percentage.
        """

        candidates = [

            decision_result.get(
                "confidence"
            ),

            decision_result.get(
                "final_confidence"
            ),

            decision_result.get(
                "confidence_score"
            ),

        ]

        for value in candidates:

            if value is not None:

                confidence = self._number(
                    value
                )

                if 0 <= confidence <= 1:

                    confidence *= 100

                return max(
                    0.0,
                    min(
                        100.0,
                        confidence,
                    ),
                )

        return 0.0

    # ==================================================================
    # REASON
    # ==================================================================

    def generate_reason(
        self,
        sell_wait,
        market,
        buyer,
        net_profit,
        risk_level,
        confidence,
        decision_result,
        logistics_result,
    ):
        """
        Generates a reason consistent with the final recommendation.
        """

        reasons = []

        # ==============================================================
        # FINAL DECISION
        # ==============================================================

        if sell_wait == "SELL NOW":

            reasons.append(
                "The available transaction is profitable, "
                "with acceptable risk and sufficient confidence."
            )

        elif sell_wait == "SELL WITH CAUTION":

            reasons.append(
                "The available transaction is profitable, "
                "but the risk or confidence conditions require caution."
            )

        else:

            reasons.append(
                "The current available transaction does not "
                "provide a sufficiently attractive outcome to sell now."
            )

        # ==============================================================
        # NET PROFIT
        # ==============================================================

        if net_profit > 0:

            reasons.append(
                f"The expected net profit is "
                f"₹{net_profit:,.2f}."
            )

        elif net_profit < 0:

            reasons.append(
                f"The best available execution option produces "
                f"a negative expected net profit of "
                f"₹{abs(net_profit):,.2f}."
            )

            reasons.append(
                "Therefore, the system recommends waiting or "
                "reassessing the available buyer, price, or market."
            )

        else:

            reasons.append(
                "The expected net profit is approximately zero."
            )

        # ==============================================================
        # RISK
        # ==============================================================

        if risk_level == "LOW":

            reasons.append(
                "The selected transaction has a low risk level."
            )

        elif risk_level == "MEDIUM":

            reasons.append(
                "The selected transaction has a medium risk level."
            )

        elif risk_level == "HIGH":

            reasons.append(
                "The selected transaction has a high risk level."
            )

        # ==============================================================
        # MARKET
        # ==============================================================

        if market != "NOT AVAILABLE":

            reasons.append(
                f"{market} is the selected market based on "
                f"the available market and logistics signals."
            )

        # ==============================================================
        # BUYER
        # ==============================================================

        if buyer != "NOT AVAILABLE":

            reasons.append(
                f"{buyer} is the selected buyer based on "
                f"buyer matching, auction, risk and profit signals."
            )

        # ==============================================================
        # CONFIDENCE
        # ==============================================================

        if confidence >= 70:

            reasons.append(
                f"The recommendation confidence is high at "
                f"{confidence:.2f}%."
            )

        elif confidence >= 50:

            reasons.append(
                f"The recommendation confidence is moderate at "
                f"{confidence:.2f}%."
            )

        else:

            reasons.append(
                f"The recommendation confidence is limited at "
                f"{confidence:.2f}%."
            )

        return " ".join(
            reasons
        )

    # ==================================================================
    # GENERATE FINAL RECOMMENDATION
    # ==================================================================

    def generate(
        self,
        decision_result,
        auction_result,
        risk_result,
        profit_result,
        logistics_result,
    ):
        """
        Generates the final seven-field recommendation.
        """

        print()
        print("=" * 70)
        print("GENERATING FINAL AI RECOMMENDATION")
        print("=" * 70)

        # ==============================================================
        # NET PROFIT
        # ==============================================================

        net_profit = self.get_net_profit(
            decision_result,
            profit_result,
        )

        # ==============================================================
        # RISK
        # ==============================================================

        risk_level = self.get_risk_level(
            decision_result,
            risk_result,
        )

        # ==============================================================
        # CONFIDENCE
        # ==============================================================

        confidence = self.get_confidence(
            decision_result,
        )

        # ==============================================================
        # MARKET
        # ==============================================================

        market = self.choose_market(
            decision_result,
            logistics_result,
        )

        # ==============================================================
        # BUYER
        # ==============================================================

        buyer = self.choose_buyer(
            decision_result,
            profit_result,
            risk_result,
            auction_result,
        )

        # ==============================================================
        # SELL / WAIT
        # ==============================================================

        sell_wait = self.determine_sell_wait(
            decision_result,
            net_profit,
            risk_level,
            confidence,
        )

        # ==============================================================
        # REASON
        # ==============================================================

        reason = self.generate_reason(
            sell_wait,
            market,
            buyer,
            net_profit,
            risk_level,
            confidence,
            decision_result,
            logistics_result,
        )

        # ==============================================================
        # FINAL RESULT
        # ==============================================================

        result = {

            "sell_now_vs_wait":
                sell_wait,

            "choose_market":
                market,

            "choose_buyer":
                buyer,

            "expected_net_profit":
                round(
                    net_profit,
                    2,
                ),

            "risk_level":
                risk_level,

            "confidence":
                round(
                    confidence,
                    2,
                ),

            "reason":
                reason,

        }

        return result

    # ==================================================================
    # VALIDATE
    # ==================================================================

    def validate(
        self,
        result,
    ):
        """
        Validates the final seven required outputs.
        """

        required_fields = [

            "sell_now_vs_wait",

            "choose_market",

            "choose_buyer",

            "expected_net_profit",

            "risk_level",

            "confidence",

            "reason",

        ]

        # --------------------------------------------------------------
        # Required fields
        # --------------------------------------------------------------

        for field in required_fields:

            if field not in result:

                raise RuntimeError(
                    f"Final recommendation missing: {field}"
                )

        # --------------------------------------------------------------
        # Sell/Wait
        # --------------------------------------------------------------

        valid_decisions = {

            "SELL NOW",

            "SELL WITH CAUTION",

            "WAIT / REASSESS",

        }

        if result[
            "sell_now_vs_wait"
        ] not in valid_decisions:

            raise RuntimeError(
                "Invalid final Sell/Wait decision: "
                f"{result['sell_now_vs_wait']}"
            )

        # --------------------------------------------------------------
        # Market
        # --------------------------------------------------------------

        if not str(
            result["choose_market"]
        ).strip():

            raise RuntimeError(
                "Choose Market is empty."
            )

        # --------------------------------------------------------------
        # Buyer
        # --------------------------------------------------------------

        if not str(
            result["choose_buyer"]
        ).strip():

            raise RuntimeError(
                "Choose Buyer is empty."
            )

        # --------------------------------------------------------------
        # Net Profit
        # --------------------------------------------------------------

        if not isinstance(
            result["expected_net_profit"],
            (int, float),
        ):

            raise RuntimeError(
                "Expected Net Profit must be numeric."
            )

        # --------------------------------------------------------------
        # Risk
        # --------------------------------------------------------------

        valid_risk_levels = {

            "LOW",

            "MEDIUM",

            "HIGH",

        }

        if result[
            "risk_level"
        ] not in valid_risk_levels:

            raise RuntimeError(
                "Invalid risk level: "
                f"{result['risk_level']}"
            )

        # --------------------------------------------------------------
        # Confidence
        # --------------------------------------------------------------

        confidence = self._number(
            result["confidence"]
        )

        if not (
            0 <= confidence <= 100
        ):

            raise RuntimeError(
                "Confidence must be between 0 and 100."
            )

        # --------------------------------------------------------------
        # Reason
        # --------------------------------------------------------------

        if not str(
            result["reason"]
        ).strip():

            raise RuntimeError(
                "Reason is empty."
            )

        return True


# ======================================================================
# EXISTING RESULT ADAPTER
# ======================================================================

def build_existing_decision_result():
    """
    Optional adapter for the existing Decision Intelligence Engine.

    The main verification uses already verified outputs below.

    This function is retained so the final layer can later be connected
    directly to the existing Decision Intelligence implementation.
    """

    try:

        from app.decision.decision_engine import (
            DecisionIntelligenceEngine
        )

    except ImportError:

        try:

            from decision_engine import (
                DecisionIntelligenceEngine
            )

        except ImportError:

            return {}

    try:

        engine = DecisionIntelligenceEngine()

    except Exception:

        return {}

    possible_methods = [

        "process",

        "run",

        "generate_decision",

        "make_decision",

    ]

    for method_name in possible_methods:

        method = getattr(
            engine,
            method_name,
            None,
        )

        if method is None:
            continue

        try:

            result = method(

                crop=CROP,

                quantity_kg=QUANTITY_KG,

                quality_grade=QUALITY_GRADE,

                district=ORIGIN_DISTRICT,

                market=ORIGIN_MARKET,

                current_price=CURRENT_PRICE,

            )

            if isinstance(
                result,
                dict,
            ):

                return result

        except TypeError:

            continue

        except Exception:

            continue

    for attribute in [

        "result",

        "final_result",

        "decision_result",

        "last_result",

    ]:

        result = getattr(
            engine,
            attribute,
            None,
        )

        if isinstance(
            result,
            dict,
        ):

            return result

    return {}


# ======================================================================
# RESULT NORMALIZATION
# ======================================================================

def normalize_result(
    result,
):
    """
    Flattens common nested result structures.
    """

    if result is None:

        return {}

    if not isinstance(
        result,
        dict,
    ):

        return {}

    normalized = dict(
        result
    )

    nested_keys = [

        "final_decision",

        "decision",

        "recommendation",

        "financial",

        "market",

        "risk",

        "confidence",

    ]

    for key in nested_keys:

        nested = result.get(
            key
        )

        if isinstance(
            nested,
            dict,
        ):

            for (
                child_key,
                value,
            ) in nested.items():

                if child_key not in normalized:

                    normalized[
                        child_key
                    ] = value

    return normalized


# ======================================================================
# VERIFIED EXISTING ARCHITECTURE OUTPUTS
# ======================================================================

def build_verified_test_results():
    """
    These values represent the already verified outputs from the
    existing architecture.

    They are NOT new predictions.

    They are used only to test the final aggregation layer.
    """

    # ==============================================================
    # DECISION INTELLIGENCE
    # ==============================================================

    decision_result = {

        "recommendation":
            "SELL WITH CAUTION",

        "decision_score":
            72.02,

        "risk_score":
            41.77,

        "risk_level":
            "MEDIUM",

        "confidence":
            76.96,

        "best_market":
            "Gandhinagar APMC",

        "net_profit":
            1000826.36,

    }

    # ==============================================================
    # AI AUCTION
    # ==============================================================

    auction_result = {

        "winner":
            "Buyer_01865",

        "buyer_name":
            "Buyer_01865",

        "winning_bid":
            2845.52,

    }

    # ==============================================================
    # RISK-AWARE BIDDING
    # ==============================================================

    risk_result = {

        "recommended_buyer":
            "Buyer_01865",

        "buyer_name":
            "Buyer_01865",

        "combined_risk":
            8.32,

        "risk_level":
            "LOW",

        "risk_aware_score":
            96.26,

    }

    # ==============================================================
    # NET PROFIT OPTIMIZATION
    # ==============================================================

    profit_result = {

        "buyer_name":
            "Buyer_01865",

        "net_profit":
            -772634.03,

        "profitability":
            "NOT_PROFITABLE",

    }

    # ==============================================================
    # LOGISTICS OPTIMIZATION
    # ==============================================================

    logistics_result = {

        "destination":
            "Kheda",

        "best_destination":
            "Kheda",

        "transport_cost":
            369.25,

        "delay_hours":
            2.15,

        "damage_percentage":
            1.20,

        "logistics_risk":
            10.79,

        "logistics_score":
            93.65,

    }

    return (
        decision_result,
        auction_result,
        risk_result,
        profit_result,
        logistics_result,
    )


# ======================================================================
# DYNAMIC DECISION LOGIC TEST
# ======================================================================

def test_dynamic_decision_logic(
    engine,
):
    """
    Verifies that all three final decision states are possible.

        SELL NOW
        SELL WITH CAUTION
        WAIT / REASSESS
    """

    print()
    print("=" * 70)
    print("DYNAMIC SELL / WAIT LOGIC TEST")
    print("=" * 70)

    # ==============================================================
    # CASE 1
    # PROFITABLE + LOW RISK + HIGH CONFIDENCE
    # ==============================================================

    result = engine.determine_sell_wait(
        {},
        500000.00,
        "LOW",
        85.0,
    )

    if result != "SELL NOW":

        raise RuntimeError(
            "Dynamic logic Case 1 failed. "
            f"Expected SELL NOW, got {result}"
        )

    print(
        "✓ Case 1: SELL NOW"
    )

    # ==============================================================
    # CASE 2
    # PROFITABLE + MEDIUM RISK
    # ==============================================================

    result = engine.determine_sell_wait(
        {},
        500000.00,
        "MEDIUM",
        80.0,
    )

    if result != "SELL WITH CAUTION":

        raise RuntimeError(
            "Dynamic logic Case 2 failed. "
            f"Expected SELL WITH CAUTION, got {result}"
        )

    print(
        "✓ Case 2: SELL WITH CAUTION"
    )

    # ==============================================================
    # CASE 3
    # NEGATIVE PROFIT
    # ==============================================================

    result = engine.determine_sell_wait(
        {},
        -772634.03,
        "LOW",
        76.96,
    )

    if result != "WAIT / REASSESS":

        raise RuntimeError(
            "Dynamic logic Case 3 failed. "
            f"Expected WAIT / REASSESS, got {result}"
        )

    print(
        "✓ Case 3: WAIT / REASSESS"
    )

    # ==============================================================
    # CASE 4
    # ZERO PROFIT
    # ==============================================================

    result = engine.determine_sell_wait(
        {},
        0.0,
        "LOW",
        90.0,
    )

    if result != "WAIT / REASSESS":

        raise RuntimeError(
            "Dynamic logic Case 4 failed. "
            f"Expected WAIT / REASSESS, got {result}"
        )

    print(
        "✓ Case 4: ZERO PROFIT → WAIT / REASSESS"
    )

    # ==============================================================
    # CASE 5
    # PROFITABLE + HIGH RISK
    # ==============================================================

    result = engine.determine_sell_wait(
        {},
        500000.00,
        "HIGH",
        85.0,
    )

    if result != "SELL WITH CAUTION":

        raise RuntimeError(
            "Dynamic logic Case 5 failed. "
            f"Expected SELL WITH CAUTION, got {result}"
        )

    print(
        "✓ Case 5: HIGH RISK → SELL WITH CAUTION"
    )

    # ==============================================================
    # CASE 6
    # PROFITABLE + LOW CONFIDENCE
    # ==============================================================

    result = engine.determine_sell_wait(
        {},
        500000.00,
        "LOW",
        40.0,
    )

    if result != "WAIT / REASSESS":

        raise RuntimeError(
            "Dynamic logic Case 6 failed. "
            f"Expected WAIT / REASSESS, got {result}"
        )

    print(
        "✓ Case 6: LOW CONFIDENCE → WAIT / REASSESS"
    )

    print()
    print(
        "✓ ALL DYNAMIC DECISION RULES PASSED"
    )


# ======================================================================
# MAIN TEST
# ======================================================================

def main():

    print()
    print("=" * 70)
    print("FINAL AI RECOMMENDATION TEST")
    print("=" * 70)

    print()
    print("Using only:")

    print(
        "✓ Existing Decision Intelligence output"
    )

    print(
        "✓ Existing AI Auction output"
    )

    print(
        "✓ Existing Risk-Aware Bidding output"
    )

    print(
        "✓ Existing Net Profit Optimization output"
    )

    print(
        "✓ Existing Logistics Optimization output"
    )

    print()
    print("No new ML model.")
    print("No new dataset.")
    print("No model retraining.")
    print("No dataset modification.")
    print("No AI Agent.")

    # ==============================================================
    # VERIFIED OUTPUTS
    # ==============================================================

    (
        decision_result,
        auction_result,
        risk_result,
        profit_result,
        logistics_result,
    ) = build_verified_test_results()

    # ==============================================================
    # ENGINE
    # ==============================================================

    engine = FinalAIRecommendationEngine()

    # ==============================================================
    # TEST ALL DECISION STATES
    # ==============================================================

    test_dynamic_decision_logic(
        engine
    )

    # ==============================================================
    # GENERATE CURRENT TRANSACTION RECOMMENDATION
    # ==============================================================

    final_result = engine.generate(

        decision_result,

        auction_result,

        risk_result,

        profit_result,

        logistics_result,

    )

    # ==============================================================
    # VALIDATE
    # ==============================================================

    engine.validate(
        final_result
    )

    # ==============================================================
    # PRINT FINAL RECOMMENDATION
    # ==============================================================

    print()
    print("=" * 70)
    print("FINAL AI RECOMMENDATION")
    print("=" * 70)

    print()

    print(
        f"Sell Now vs Wait : "
        f"{final_result['sell_now_vs_wait']}"
    )

    print()

    print(
        f"Choose Market    : "
        f"{final_result['choose_market']}"
    )

    print()

    print(
        f"Choose Buyer     : "
        f"{final_result['choose_buyer']}"
    )

    print()

    print(
        f"Expected Net Profit : "
        f"₹{final_result['expected_net_profit']:,.2f}"
    )

    print()

    print(
        f"Risk Level       : "
        f"{final_result['risk_level']}"
    )

    print()

    print(
        f"Confidence       : "
        f"{final_result['confidence']:.2f}%"
    )

    print()

    print(
        "Reason           :"
    )

    print(
        final_result["reason"]
    )

    # ==============================================================
    # EXPECTED CURRENT RESULT
    # ==============================================================

    print()
    print("=" * 70)
    print("CURRENT TRANSACTION DECISION CHECK")
    print("=" * 70)

    current_profit = final_result[
        "expected_net_profit"
    ]

    current_decision = final_result[
        "sell_now_vs_wait"
    ]

    if current_profit < 0:

        if current_decision != "WAIT / REASSESS":

            raise RuntimeError(
                "Current transaction has negative expected "
                "net profit but final recommendation is not "
                "WAIT / REASSESS."
            )

        print()
        print(
            "✓ Negative expected profit correctly produced:"
        )

        print(
            "  WAIT / REASSESS"
        )

    elif current_profit > 0:

        print()
        print(
            "✓ Positive expected profit detected."
        )

        print(
            f"  Final decision: {current_decision}"
        )

    else:

        print()
        print(
            "✓ Zero expected profit correctly evaluated."
        )

    # ==============================================================
    # FINAL STATUS
    # ==============================================================

    print()
    print("=" * 70)
    print("FINAL AI RECOMMENDATION STATUS")
    print("=" * 70)

    print()
    print(
        "✓ Sell Now vs Wait       : VERIFIED"
    )

    print(
        "✓ Choose Market          : VERIFIED"
    )

    print(
        "✓ Choose Buyer           : VERIFIED"
    )

    print(
        "✓ Expected Net Profit    : VERIFIED"
    )

    print(
        "✓ Risk Level             : VERIFIED"
    )

    print(
        "✓ Confidence             : VERIFIED"
    )

    print(
        "✓ Reason                 : VERIFIED"
    )

    print()
    print(
        "✓ Dynamic decision logic : VERIFIED"
    )

    print(
        "✓ SELL NOW scenario      : VERIFIED"
    )

    print(
        "✓ SELL WITH CAUTION      : VERIFIED"
    )

    print(
        "✓ WAIT / REASSESS        : VERIFIED"
    )

    print()
    print("=" * 70)

    print(
        "✓ FINAL AI RECOMMENDATION FULLY COMPLETED"
    )

    print("=" * 70)

    print()
    print(
        "FINAL AI RECOMMENDATION STATUS: COMPLETE"
    )

    return final_result


# ======================================================================
# ENTRY POINT
# ======================================================================

if __name__ == "__main__":

    try:

        main()

    except KeyboardInterrupt:

        print()
        print(
            "✗ Final AI Recommendation test "
            "interrupted by user."
        )

        sys.exit(130)

    except Exception as exc:

        print()
        print("=" * 70)

        print(
            "✗ FINAL AI RECOMMENDATION FAILED"
        )

        print("=" * 70)

        print()

        print(
            f"{type(exc).__name__}: {exc}"
        )

        print()

        traceback.print_exc()

        sys.exit(1)